name: mdcharts_example
description: Demonstrates how to use the mdcharts package.

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  mdcharts:
    path: ../

  intl: ^0.20.2
  rxdart: ^0.28.0
  flutter_colorpicker: ^1.1.0

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
