name: mdcharts
version: 4.0.0-dev.12
homepage: https://github.com/marchdev-tk/mdcharts
repository: https://github.com/marchdev-tk/mdcharts
issue_tracker: https://github.com/marchdev-tk/mdcharts/issues
description: march.dev charts library. Provides highly customizable and configurable charts.

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  
  cross_platform: ^3.0.1
  flinq: ^2.0.2
  rxdart: ^0.27.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
